platform :ios, '14.0'

target 'Swift-Player' do 
  use_frameworks! 
  pod 'MLYSDK',:git => 'https://github.com/mlytics/mly-stream-sdk-ios-avplayer.git'
  pod 'MLYAVPlayer',:git => 'https://github.com/mlytics/mly-stream-sdk-ios-avplayer.git'

  pod 'Sentry', :modular_headers => true
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['SWIFT_VERSION'] = '5.10'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['OTHER_LDFLAGS'] = '$(inherited) -ObjC -all_load'

      # Sentry 特定設定
      if target.name == 'Sentry'
        config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'NO'
        config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = 'Sentry-Swift.h'
      end

      # SwiftProtobuf 特定設定
      if target.name == 'SwiftProtobuf'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
        config.build_settings['ENABLE_TESTABILITY'] = 'NO'
        config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
        config.build_settings['OTHER_SWIFT_FLAGS'] = '$(inherited) -D SWIFT_PACKAGE'
      end

      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
