platform :ios, '14.0'

target 'Swift-Player' do 
  use_frameworks! 
  pod 'MLYSDK',:git => 'https://github.com/mlytics/mly-stream-sdk-ios-avplayer.git'
  pod 'MLYAVPlayer',:git => 'https://github.com/mlytics/mly-stream-sdk-ios-avplayer.git'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      config.build_settings['ENABLE_SWIFT_RUNTIME'] = 'YES'
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] = ['$(SDKROOT)/System/Library/Frameworks', '$(inherited)']
      config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = ['$(inherited)', '@executable_path/Frameworks', '@loader_path/Frameworks', '$(TOOLCHAIN_DIR)/usr/lib/swift/iphonesimulator']
      config.build_settings['OTHER_LDFLAGS'] = ['$(inherited)', '-ObjC', '-all_load', '-L$(TOOLCHAIN_DIR)/usr/lib/swift/iphonesimulator']
      config.build_settings['SWIFT_INCLUDE_PATHS'] = ['$(TOOLCHAIN_DIR)/usr/lib/swift', '$(inherited)']
      
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end
  end
end
