# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'swift-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-demo
  pod 'SnapKit', '~> 5.6.0'
pod 'MLYSDK',:git => 'https://github.com/mlytics/mly-stream-sdk-avplayer.git'
end
