name: iOS Simulator Build

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * MON'    

jobs:
  build:
    name: Build for iOS Simulator
    runs-on: macos-14

    strategy:
      matrix:
        project_dir:
          - Examples/Swift-Player
        scheme:
          - Swift-Player

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3'

      - name: Check environment
        run: |
          echo "Architecture: $(uname -m)"
          echo "OS Version: $(sw_vers)"
          echo "Xcode Version: $(xcodebuild -version)"
          echo "Swift Version: $(swift --version)"

      - name: Clean Pods
        run: |
          pod deintegrate "${{ matrix.project_dir }}/${{ matrix.scheme }}.xcodeproj"
          rm -rf "${{ matrix.project_dir }}/Pods"
          rm -rf "${{ matrix.project_dir }}/${{ matrix.scheme }}.xcworkspace"
          rm -rf "${{ matrix.project_dir }}/Podfile.lock"

      - name: Install CocoaPods dependencies
        run: |
          sudo gem install cocoapods
          pod install --project-directory=${{ matrix.project_dir }}

      - name: Build for iOS Simulator
        run: |
          xcodebuild -workspace "${{ matrix.project_dir }}/${{ matrix.scheme }}.xcworkspace" \
                     -scheme "${{ matrix.scheme }}" \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.5' \
                     CODE_SIGNING_ALLOWED=NO \
                     ARCHS="arm64" \
                     clean build
