name: iOS Simulator Build

on:
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * MON'    

jobs:
  build:
    name: Build for iOS Simulator
    runs-on: macos-latest

    strategy:
      matrix:
        project_dir:
          - Examples/Swift-Player
        scheme:
          - Swift-Player
        os: [latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Clean Pods
        run: |
          pod deintegrate "${{ matrix.project_dir }}/${{ matrix.scheme }}.xcodeproj"
          rm -rf "${{ matrix.project_dir }}/Pods"
          rm -rf "${{ matrix.project_dir }}/${{ matrix.scheme }}.xcworkspace"
          rm -rf "${{ matrix.project_dir }}/Podfile.lock"

      - name: Install CocoaPods dependencies
        run: |
          sudo gem install cocoapods
          pod install --project-directory=${{ matrix.project_dir }}

      - name: Build for iOS Simulator
        run: |
          xcodebuild -workspace "${{ matrix.project_dir }}/${{ matrix.scheme }}.xcworkspace" \
                     -scheme "${{ matrix.scheme }}" \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
                     CODE_SIGN_IDENTITY="" \
                     PROVISIONING_PROFILE_SPECIFIER="" \
                     CODE_SIGNING_ALLOWED=NO \
                     ONLY_ACTIVE_ARCH=NO \
                     BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
                     ENABLE_BITCODE=NO \
                     ARCHS="arm64" \
                     SWIFT_VERSION=5.0 \
                     OTHER_LDFLAGS="-ObjC -all_load" \
                     -UseModernBuildSystem=YES \
                     clean build
